### ISSUE TITLE
Bootloader is Unthemed

### ISSUE THREAD

**Issue by sysrich** [ProjectGreybeard/bugs#1]
![Screenshot from 2023-02-15 17-01-37](https://user-images.githubusercontent.com/1197728/219082555-b1c815fe-5cc1-4493-ba83-1bc700e29ed9.png)

**Comment by sysrich** [comment]
Installed system is also unthemed
![Screenshot from 2023-02-15 17-03-20](https://user-images.githubusercontent.com/1197728/219083039-d3ac3383-c5fd-4e7b-af3a-d9cb1f003039.png)

**Comment by sysrich** [comment]
Not sure we'll actually 'fix' this.. it is perfectly functionaly and more minimal this way :)

**Comment by sfalken** [comment]
I vote for just leaving it like it is.  For what that's worth.

**Comment by sysrich** [comment]
Closing then :)
