### ISSUE TITLE
Screenshot application: grim

### ISSUE THREAD

**Issue by m4u9** [ProjectGreybeard/bugs#13]
grim is a very simple tool to take screenshots. would be nice to have and bind it to the print screen key or any other meta binding

**Comment by sfalken** [comment]
It's already in the default install, do we just need to get the keybinding sorted?

**Comment by m4u9** [comment]
if it is already installed I must have missed it. Either way
a keybinding would be a great addition

**Comment by m4u9** [comment]
The simplest way is to add a line with key bind in 50-greybeard.conf.

For example we bind the `PrtSc` key to `grim` with the following line:

`bindsym Print exec grim`

This is a very basic setup that saves a screenshot of the whole visible area in your home directory. I think it's good enough, for more complex screenshot tasks there are many flatpak applications available that can do it.

**Comment by m4u9** [comment]
Merged and Fixed
