### ISSUE TITLE
Some audio key binfding such as mic toggle don't work

### ISSUE THREAD

**Issue by m4u9** [ProjectGreybeard/bugs#18]
This is because 50-greybeard.cong binds the keys to `pactl` which controls pavucontrol. 

The fix is simple enough, we need to install package pulseaudio-utils which provides the `pactl` command.

**Comment by m4u9** [comment]
@sfalken since you already have a recent SR open to the patterns, do you want to add this one too? Up to you, it can also be done later :)

**Comment by sfalken** [comment]
https://build.opensuse.org/request/show/1070289

**Comment by m4u9** [comment]
thanks!

**Comment by m4u9** [comment]
This is fixed
