### ISSUE TITLE
[Feature] Include blueman for easier bluetooth connectivity

### ISSUE THREAD

**Issue by m4u9** [ProjectGreybeard/bugs#19]
Blueman is a tool to manage bluetooth devices and I'm the package maintainer of it in Factory. 

It's easy to use and can be launched at startup by adding this line to the 50-greybeard.conf file:

`exec_always /usr/bin/blueman-applet`

**Comment by sfalken** [comment]
https://build.opensuse.org/request/show/1077614

**Comment by m4u9** [comment]
We also need `exec_always /usr/bin/blueman-applet` in the sway conf file

**Comment by sfalken** [comment]
Aye, not much point until the application is there, to be adding it though  =P

**Comment by m4u9** [comment]
but it's there now is it not? I saw the SR was accepted

**Comment by sfalken** [comment]
It probably is now, I usually give it a little bit for OBS to generate a new image.

**Comment by sfalken** [comment]
blueman is now in, but we need to do something with polkit, I *think*, as rfkill is now requiring the root password to be entered on each boot, for bluetooth functionality

**Comment by mcepl** [comment]
Some modification of this?

```
stitny:rules.d# cat /etc/polkit-1/rules.d/10-rfkill.rules 
/* Allow users in wheel group to use blueman feature requiring root without authentication */
polkit.addRule(function(action, subject) {
    if ((action.id == "org.blueman.network.setup" ||
         action.id == "org.blueman.dhcp.client" ||
         action.id == "org.blueman.rfkill.setstate" ||
         action.id == "org.blueman.pppd.pppconnect") &&
        subject.isInGroup("wheel")) {

        return polkit.Result.YES;
    }
});
stitny:rules.d# 
```

**Comment by sfalken** [comment]
Polkit issue fixed.
https://build.opensuse.org/request/show/1088482

**Comment by mcepl** [comment]
We are missing the `wheel` group.

**Comment by mcepl** [comment]
THis could be probably closed.
