### ISSUE TITLE
[Enhancement] Add gap between windows

### ISSUE THREAD

**Issue by m4u9** [ProjectGreybeard/bugs#20]
I think this is down to personal taste but a 5px gap between windows is kinda nice and sacrifices just a little real estate but makes things look tidier.

Can be tested with  command `swaymsg gaps inner 5` and create new workspace to see the effect.

To make it permanent just add `gaps inner 5` to 50-greybeard.conf file or any *.conf file of your preference inside config.d folder

Preview:
![screenshot_2023-03-16-175140](https://user-images.githubusercontent.com/44322817/225580317-e93a3cc7-562c-4cb0-b30a-0397eb152013.png)

**Comment by mcepl** [comment]
This is a personal preference, you could go and fix it in your `~/.config/sway` directory.
