### ISSUE TITLE
swaynag not installed by default

### ISSUE THREAD

**Issue by m4u9** [ProjectGreybeard/bugs#23]
We need swaynag to be added to the pattern, so that we can display warning messages etc, already set in the basic config

**Comment by sfalken** [comment]
https://build.opensuse.org/request/show/1077614

**Comment by m4u9** [comment]
thanks for adding it to the pattern, however it turns out swaynag is not needed because we use a custom $mode_system config instead. I guess swaynag could be removed from the pattern in a later update.
