### ISSUE TITLE
[Enhancement]  Add clipman for clipboard management

### ISSUE THREAD

**Issue by sfalken** [ProjectGreybeard/bugs#25]
By default, in sway, the contents of the clipboard are wiped, whenever the window you copied from is closed

clipman is a small clipboard manager designed specifically for wayland

**Comment by sfalken** [comment]
~/.config/sway/config

exec wl-paste -t text --watch clipman store --no-persist

**Comment by mcepl** [comment]
Also, you need `wl-clipboard` for that `wl-paste` command.

**Comment by sfalken** [comment]
https://build.opensuse.org/request/show/1079526

**Comment by mcepl** [comment]
This could be closed.
