### ISSUE TITLE
Set LC_ALL and/or LANG somewhere by default

### ISSUE THREAD

**Issue by sfalken** [ProjectGreybeard/bugs#27]
When launching distrobox containers (and some other stuff) at present, the locale is being set to C, which causes issues with some stuff.    I'm not entirely certain what we should be using, as my local workaround, I've just set `export LC_ALL=en_US.utf8` in my `~/.bashrc`  Maybe add something to set it, in the install script or firstboot?

**Comment by mcepl** [comment]
It also doesn't help that distrobox Tumbleweed images don't have (IIRC, I have already installed it) full `glibc-locale` package. Some of us don’t have English as a native language.

**Comment by sfalken** [comment]
https://build.opensuse.org/request/show/1108678
