### ISSUE TITLE
[error] Missing required resource files loading waybar

### ISSUE THREAD

**Issue by sysrich** [ProjectGreybeard/bugs#6]
@m4u9 how come it works for you?

![Screenshot from 2023-02-20 18-10-02](https://user-images.githubusercontent.com/1197728/220167245-4b7e9c42-13bb-4e91-a49c-8578307a78ec.png)

**Comment by m4u9** [comment]
oversight from my part... we need  style.css file and because of the new conflict introduced with waybar-upstream package, it got removed. I will send the necessary PR and SR to include it.

**Comment by m4u9** [comment]
It worked for me because I was using an older image and had a copy of the file in my home config

**Comment by m4u9** [comment]
The file is already here: https://github.com/ProjectGreybeard/branding/blob/main/config/waybar/style.css

This SR makes sure it's installed: ~~https://build.opensuse.org/request/show/1066892~~ https://build.opensuse.org/request/show/1066959

**Comment by m4u9** [comment]
This should be fixed now

**Comment by mcepl** [comment]
As it was said, closing, because it has been fixed already.
