### ISSUE TITLE
[regression] flatpak applications don't show up in application launchers

### ISSUE THREAD

**Issue by m4u9** [ProjectGreybeard/bugs#7]
In a fresh install flatpak applications no longer show in application menues like wofi and sway-launcher-desktop.

Running `flatpak run org.mozilla.firefox` prompts a warning suggesting there may be an issue with XDG_DATA_DIR

**Comment by sysrich** [comment]
Strange, that was working for me in previous images

**Comment by m4u9** [comment]
yea it worked for me previously too but was t sure because I player with configs a lot… so I guess it’s a regression

**Comment by m4u9** [comment]
I narrowed it down and the regression was introduced by this: https://github.com/ProjectGreybeard/branding/pull/6

I am not sure of why but it seems it conflicts with flatpak.sh

**Comment by m4u9** [comment]
The solution is that the filename needs to be renamed from autostartsway.sh to sway.sh. T

**Comment by m4u9** [comment]
Fixed
