### ISSUE TITLE
firstboot wizard firtboot-mod runs at every system startup

### ISSUE THREAD

**Issue by m4u9** [ProjectGreybeard/bugs#8]
This is  due to the fact that the script is executed inside the sway config file in /sway/config.d/50-firstboot.conf. We need a smarter way to execute this.  I could not reproduce this when the file lived inside ~/.config/sway. 

Should not be too hard to fix this, for example 50-firstboot.conf could execute a .desktop file that then gets cleaned up. mod-firstboot script already has that command for cleanup.

**Comment by sysrich** [comment]
the firstboot script just needs to delete itself..and/or delete /etc/sway/config.d/50-firstboot.conf

**Comment by m4u9** [comment]
i thought about that but felt a bit extreme. maybe it could rename itself instead?

**Comment by sysrich** [comment]
well why not put the firstboot conf in skel and then delete it from the users home? Doesn't really make sense as a permenant system wide config in /etc

**Comment by m4u9** [comment]
good point. I think “this is the way”

**Comment by m4u9** [comment]
should be fixed by this SR: https://build.opensuse.org/request/show/1068988

**Comment by m4u9** [comment]
Will add the revised mod-firstboot script to this github repo later

**Comment by m4u9** [comment]
This has been fixed, and  then replaced by a newer gb-firstboot script
